/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
	_id: string;
	_type: 'siteSettings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	navLinks?: Array<{
		label: string;
		href: string;
		_key: string;
	}>;
	socialLinks?: Array<{
		platform: 'instagram' | 'twitter' | 'opensea' | 'etsy';
		url: string;
		_key: string;
	}>;
	contactEmail?: string;
	nextDropAt?: string;
	faqs?: Array<{
		question: string;
		answer: string;
		_key: string;
	}>;
	ctaHeading?: string;
	ctaBody?: string;
	ctaButtonLabel?: string;
	ctaButtonHref?: string;
};

export type Subscriber = {
	_id: string;
	_type: 'subscriber';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	email: string;
	subscribedAt?: string;
	source?: string;
};

export type Nomination = {
	_id: string;
	_type: 'nomination';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	birdName: string;
	slug: Slug;
	voteCount?: number;
	status?: 'approved' | 'pending' | 'rejected';
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type RarityTier = {
	_id: string;
	_type: 'rarityTier';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	level: 1 | 2 | 3 | 4 | 5;
	label: string;
	maxPhysical: number;
	maxDigital: number;
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Post = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	excerpt?: string;
	category?: string;
	tags?: Array<string>;
	publishedAt: string;
	coverImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'normal' | 'h2' | 'h3' | 'blockquote';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				_type: 'image';
				_key: string;
		  }
	>;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x: number;
	y: number;
	height: number;
	width: number;
};

export type BirdReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'bird';
};

export type Card = {
	_id: string;
	_type: 'card';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	bird: BirdReference;
	slug: Slug;
	smallName: string;
	bigName: string;
	edition: string;
	artwork: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	accentColor?: string;
	specialty?: 'standard' | 'specialty';
	rarity: 1 | 2 | 3 | 4 | 5;
	releaseDate?: string;
	totalPrinted?: number;
	qrScans?: number;
	availability?: 'individual' | 'packOnly';
	sold?: number;
	inventory?: number;
	etsyUrl?: string;
	openseaUrl?: string;
	legacyId?: string;
};

export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Bird = {
	_id: string;
	_type: 'bird';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	commonName: string;
	slug: Slug;
	scientificName?: string;
	family?: string;
	order?: string;
	region?: Array<string>;
	conservationStatus?:
		| 'Least Concern'
		| 'Near Threatened'
		| 'Vulnerable'
		| 'Endangered'
		| 'Critically Endangered'
		| 'Extinct in the Wild'
		| 'Data Deficient';
	sizeRange?: {
		lengthMin?: number;
		lengthMax?: number;
		wingspanMin?: number;
		wingspanMax?: number;
	};
	habitat?: string;
	behavior?: string;
	weight?: string;
	lifespan?: string;
	clutch?: string;
	diet?: string;
	nest?: string;
	migration?: string;
	population?: string;
	similarSpecies?: string;
	funFacts?: Array<string>;
	audio?: {
		file?: {
			asset?: SanityFileAssetReference;
			media?: unknown;
			_type: 'file';
		};
		title?: string;
		durationSeconds?: number;
		credit?: MediaCredit;
	};
	photos?: Array<{
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		alt?: string;
		credit: MediaCredit;
		_key: string;
	}>;
	mediaFetchedAt?: string;
	eBirdSlug?: string;
	audubonSlug?: string;
	legacyId?: string;
};

export type MediaCredit = {
	_type: 'mediaCredit';
	author: string;
	license: string;
	source: 'xeno-canto' | 'wikimedia';
	sourceUrl: string;
	sourceId?: string;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| SiteSettings
	| Subscriber
	| Nomination
	| Slug
	| RarityTier
	| SanityImageAssetReference
	| Post
	| SanityImageCrop
	| SanityImageHotspot
	| BirdReference
	| Card
	| SanityFileAssetReference
	| Bird
	| MediaCredit
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: ../src/lib/queries.ts
// Variable: cardsQuery
// Query: *[_type == "card"] | order(rarity desc, bird->commonName asc) {	_id,	"slug": slug.current,	smallName,	bigName,	edition,	rarity,	specialty,	accentColor,	releaseDate,	qrScans,	availability,	artwork {		asset->{			_id,			url,			"lqip": metadata.lqip,			"aspectRatio": metadata.dimensions.aspectRatio		}	},	bird->{		commonName,		"slug": slug.current,		scientificName,		conservationStatus	}}
export type CardsQueryResult = Array<{
	_id: string;
	slug: string;
	smallName: string;
	bigName: string;
	edition: string;
	rarity: 1 | 2 | 3 | 4 | 5;
	specialty: 'specialty' | 'standard' | null;
	accentColor: string | null;
	releaseDate: string | null;
	qrScans: number | null;
	availability: 'individual' | 'packOnly' | null;
	artwork: {
		asset: {
			_id: string;
			url: string;
			lqip: string | null;
			aspectRatio: number | null;
		} | null;
	};
	bird: {
		commonName: string;
		slug: string;
		scientificName: string | null;
		conservationStatus:
			| 'Critically Endangered'
			| 'Data Deficient'
			| 'Endangered'
			| 'Extinct in the Wild'
			| 'Least Concern'
			| 'Near Threatened'
			| 'Vulnerable'
			| null;
	};
}>;

// Source: ../src/lib/queries.ts
// Variable: cardBySlugQuery
// Query: *[_type == "card" && slug.current == $slug][0] {			_id,	"slug": slug.current,	smallName,	bigName,	edition,	rarity,	specialty,	accentColor,	releaseDate,	qrScans,	availability,	artwork {		asset->{			_id,			url,			"lqip": metadata.lqip,			"aspectRatio": metadata.dimensions.aspectRatio		}	},	bird->{		commonName,		"slug": slug.current,		scientificName,		conservationStatus	},		sold,		inventory,		etsyUrl,		openseaUrl	}
export type CardBySlugQueryResult = {
	_id: string;
	slug: string;
	smallName: string;
	bigName: string;
	edition: string;
	rarity: 1 | 2 | 3 | 4 | 5;
	specialty: 'specialty' | 'standard' | null;
	accentColor: string | null;
	releaseDate: string | null;
	qrScans: number | null;
	availability: 'individual' | 'packOnly' | null;
	artwork: {
		asset: {
			_id: string;
			url: string;
			lqip: string | null;
			aspectRatio: number | null;
		} | null;
	};
	bird: {
		commonName: string;
		slug: string;
		scientificName: string | null;
		conservationStatus:
			| 'Critically Endangered'
			| 'Data Deficient'
			| 'Endangered'
			| 'Extinct in the Wild'
			| 'Least Concern'
			| 'Near Threatened'
			| 'Vulnerable'
			| null;
	};
	sold: number | null;
	inventory: number | null;
	etsyUrl: string | null;
	openseaUrl: string | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: birdSlugsQuery
// Query: *[_type == "bird" && defined(slug.current)].slug.current
export type BirdSlugsQueryResult = Array<string>;

// Source: ../src/lib/queries.ts
// Variable: birdBySlugQuery
// Query: *[_type == "bird" && slug.current == $slug][0] {		_id,		commonName,		"slug": slug.current,		scientificName,		family,		order,		region,		conservationStatus,		sizeRange { lengthMin, lengthMax, wingspanMin, wingspanMax },		weight,		lifespan,		clutch,		diet,		nest,		migration,		population,		similarSpecies,		habitat,		behavior,		funFacts,		eBirdSlug,		audubonSlug,		audio {			title,			durationSeconds,			"url": file.asset->url,			credit { author, license, source, sourceUrl, sourceId }		},		photos[] {			_key,			alt,			image { asset->{ _id, url, "lqip": metadata.lqip, "aspectRatio": metadata.dimensions.aspectRatio } },			credit { author, license, source, sourceUrl, sourceId }		},		"cards": *[_type == "card" && bird._ref == ^._id] | order(edition asc) {				_id,	"slug": slug.current,	smallName,	bigName,	edition,	rarity,	specialty,	accentColor,	releaseDate,	qrScans,	availability,	artwork {		asset->{			_id,			url,			"lqip": metadata.lqip,			"aspectRatio": metadata.dimensions.aspectRatio		}	},	bird->{		commonName,		"slug": slug.current,		scientificName,		conservationStatus	},			openseaUrl,			etsyUrl,			sold,			inventory		}	}
export type BirdBySlugQueryResult = {
	_id: string;
	commonName: string;
	slug: string;
	scientificName: string | null;
	family: string | null;
	order: string | null;
	region: Array<string> | null;
	conservationStatus:
		| 'Critically Endangered'
		| 'Data Deficient'
		| 'Endangered'
		| 'Extinct in the Wild'
		| 'Least Concern'
		| 'Near Threatened'
		| 'Vulnerable'
		| null;
	sizeRange: {
		lengthMin: number | null;
		lengthMax: number | null;
		wingspanMin: number | null;
		wingspanMax: number | null;
	} | null;
	weight: string | null;
	lifespan: string | null;
	clutch: string | null;
	diet: string | null;
	nest: string | null;
	migration: string | null;
	population: string | null;
	similarSpecies: string | null;
	habitat: string | null;
	behavior: string | null;
	funFacts: Array<string> | null;
	eBirdSlug: string | null;
	audubonSlug: string | null;
	audio: {
		title: string | null;
		durationSeconds: number | null;
		url: string | null;
		credit: {
			author: string;
			license: string;
			source: 'wikimedia' | 'xeno-canto';
			sourceUrl: string;
			sourceId: string | null;
		} | null;
	} | null;
	photos: Array<{
		_key: string;
		alt: string | null;
		image: {
			asset: {
				_id: string;
				url: string;
				lqip: string | null;
				aspectRatio: number | null;
			} | null;
		};
		credit: {
			author: string;
			license: string;
			source: 'wikimedia' | 'xeno-canto';
			sourceUrl: string;
			sourceId: string | null;
		};
	}> | null;
	cards: Array<{
		_id: string;
		slug: string;
		smallName: string;
		bigName: string;
		edition: string;
		rarity: 1 | 2 | 3 | 4 | 5;
		specialty: 'specialty' | 'standard' | null;
		accentColor: string | null;
		releaseDate: string | null;
		qrScans: number | null;
		availability: 'individual' | 'packOnly' | null;
		artwork: {
			asset: {
				_id: string;
				url: string;
				lqip: string | null;
				aspectRatio: number | null;
			} | null;
		};
		bird: {
			commonName: string;
			slug: string;
			scientificName: string | null;
			conservationStatus:
				| 'Critically Endangered'
				| 'Data Deficient'
				| 'Endangered'
				| 'Extinct in the Wild'
				| 'Least Concern'
				| 'Near Threatened'
				| 'Vulnerable'
				| null;
		};
		openseaUrl: string | null;
		etsyUrl: string | null;
		sold: number | null;
		inventory: number | null;
	}>;
} | null;

// Source: ../src/lib/queries.ts
// Variable: birdNavQuery
// Query: *[_type == "bird" && defined(slug.current)] | order(commonName asc) {		commonName,		"slug": slug.current	}
export type BirdNavQueryResult = Array<{
	commonName: string;
	slug: string;
}>;

// Source: ../src/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(publishedAt)] | order(publishedAt desc) {		_id, title, "slug": slug.current, excerpt, category, tags, publishedAt	}
export type AllPostsQueryResult = Array<{
	_id: string;
	title: string;
	slug: string;
	excerpt: string | null;
	category: string | null;
	tags: Array<string> | null;
	publishedAt: string;
}>;

// Source: ../src/lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {		_id, title, "slug": slug.current, excerpt, category, tags, publishedAt, body	}
export type PostBySlugQueryResult = {
	_id: string;
	title: string;
	slug: string;
	excerpt: string | null;
	category: string | null;
	tags: Array<string> | null;
	publishedAt: string;
	body: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?: 'blockquote' | 'h2' | 'h3' | 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				_type: 'image';
				_key: string;
		  }
	> | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: postSlugsQuery
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt)].slug.current
export type PostSlugsQueryResult = Array<string>;

// Source: ../src/lib/queries.ts
// Variable: cardSlugsQuery
// Query: *[_type == "card" && defined(slug.current)].slug.current
export type CardSlugsQueryResult = Array<string>;

// Source: ../src/lib/queries.ts
// Variable: rarityTiersQuery
// Query: *[_type == "rarityTier"] | order(level asc) {		_id,		level,		label,		maxPhysical,		maxDigital	}
export type RarityTiersQueryResult = Array<{
	_id: string;
	level: 1 | 2 | 3 | 4 | 5;
	label: string;
	maxPhysical: number;
	maxDigital: number;
}>;

// Source: ../src/lib/queries.ts
// Variable: recentPostsQuery
// Query: *[_type == "post" && defined(publishedAt)] | order(publishedAt desc)[0...3] {		_id,		title,		"slug": slug.current,		excerpt,		category,		tags,		publishedAt,		coverImage {			alt,			asset->{ _id, url, "lqip": metadata.lqip, "aspectRatio": metadata.dimensions.aspectRatio }		}	}
export type RecentPostsQueryResult = Array<{
	_id: string;
	title: string;
	slug: string;
	excerpt: string | null;
	category: string | null;
	tags: Array<string> | null;
	publishedAt: string;
	coverImage: {
		alt: string | null;
		asset: {
			_id: string;
			url: string;
			lqip: string | null;
			aspectRatio: number | null;
		} | null;
	} | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: nominationsQuery
// Query: *[_type == "nomination" && status == "approved"]		| order(voteCount desc, birdName asc)[0...5] {		_id,		birdName,		"slug": slug.current,		voteCount	}
export type NominationsQueryResult = Array<{
	_id: string;
	birdName: string;
	slug: string;
	voteCount: number | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0] {		navLinks[] { _key, label, href },		socialLinks[] { _key, platform, url },		contactEmail,		faqs[] { _key, question, answer },		ctaHeading,		ctaBody,		ctaButtonLabel,		ctaButtonHref,		nextDropAt	}
export type SiteSettingsQueryResult =
	| {
			navLinks: null;
			socialLinks: null;
			contactEmail: null;
			faqs: null;
			ctaHeading: null;
			ctaBody: null;
			ctaButtonLabel: null;
			ctaButtonHref: null;
			nextDropAt: null;
	  }
	| {
			navLinks: Array<{
				_key: string;
				label: string;
				href: string;
			}> | null;
			socialLinks: Array<{
				_key: string;
				platform: 'etsy' | 'instagram' | 'opensea' | 'twitter';
				url: string;
			}> | null;
			contactEmail: string | null;
			faqs: Array<{
				_key: string;
				question: string;
				answer: string;
			}> | null;
			ctaHeading: string | null;
			ctaBody: string | null;
			ctaButtonLabel: string | null;
			ctaButtonHref: string | null;
			nextDropAt: string | null;
	  }
	| null;

// Query TypeMap
declare global {
	interface SanityQueries {
		'\n\t*[_type == "card"] | order(rarity desc, bird->commonName asc) {\n\t_id,\n\t"slug": slug.current,\n\tsmallName,\n\tbigName,\n\tedition,\n\trarity,\n\tspecialty,\n\taccentColor,\n\treleaseDate,\n\tqrScans,\n\tavailability,\n\tartwork {\n\t\tasset->{\n\t\t\t_id,\n\t\t\turl,\n\t\t\t"lqip": metadata.lqip,\n\t\t\t"aspectRatio": metadata.dimensions.aspectRatio\n\t\t}\n\t},\n\tbird->{\n\t\tcommonName,\n\t\t"slug": slug.current,\n\t\tscientificName,\n\t\tconservationStatus\n\t}\n}\n': CardsQueryResult;
		'\n\t*[_type == "card" && slug.current == $slug][0] {\n\t\t\n\t_id,\n\t"slug": slug.current,\n\tsmallName,\n\tbigName,\n\tedition,\n\trarity,\n\tspecialty,\n\taccentColor,\n\treleaseDate,\n\tqrScans,\n\tavailability,\n\tartwork {\n\t\tasset->{\n\t\t\t_id,\n\t\t\turl,\n\t\t\t"lqip": metadata.lqip,\n\t\t\t"aspectRatio": metadata.dimensions.aspectRatio\n\t\t}\n\t},\n\tbird->{\n\t\tcommonName,\n\t\t"slug": slug.current,\n\t\tscientificName,\n\t\tconservationStatus\n\t}\n,\n\t\tsold,\n\t\tinventory,\n\t\tetsyUrl,\n\t\topenseaUrl\n\t}\n': CardBySlugQueryResult;
		'\n\t*[_type == "bird" && defined(slug.current)].slug.current\n': BirdSlugsQueryResult;
		'\n\t*[_type == "bird" && slug.current == $slug][0] {\n\t\t_id,\n\t\tcommonName,\n\t\t"slug": slug.current,\n\t\tscientificName,\n\t\tfamily,\n\t\torder,\n\t\tregion,\n\t\tconservationStatus,\n\t\tsizeRange { lengthMin, lengthMax, wingspanMin, wingspanMax },\n\t\tweight,\n\t\tlifespan,\n\t\tclutch,\n\t\tdiet,\n\t\tnest,\n\t\tmigration,\n\t\tpopulation,\n\t\tsimilarSpecies,\n\t\thabitat,\n\t\tbehavior,\n\t\tfunFacts,\n\t\teBirdSlug,\n\t\taudubonSlug,\n\t\taudio {\n\t\t\ttitle,\n\t\t\tdurationSeconds,\n\t\t\t"url": file.asset->url,\n\t\t\tcredit { author, license, source, sourceUrl, sourceId }\n\t\t},\n\t\tphotos[] {\n\t\t\t_key,\n\t\t\talt,\n\t\t\timage { asset->{ _id, url, "lqip": metadata.lqip, "aspectRatio": metadata.dimensions.aspectRatio } },\n\t\t\tcredit { author, license, source, sourceUrl, sourceId }\n\t\t},\n\t\t"cards": *[_type == "card" && bird._ref == ^._id] | order(edition asc) {\n\t\t\t\n\t_id,\n\t"slug": slug.current,\n\tsmallName,\n\tbigName,\n\tedition,\n\trarity,\n\tspecialty,\n\taccentColor,\n\treleaseDate,\n\tqrScans,\n\tavailability,\n\tartwork {\n\t\tasset->{\n\t\t\t_id,\n\t\t\turl,\n\t\t\t"lqip": metadata.lqip,\n\t\t\t"aspectRatio": metadata.dimensions.aspectRatio\n\t\t}\n\t},\n\tbird->{\n\t\tcommonName,\n\t\t"slug": slug.current,\n\t\tscientificName,\n\t\tconservationStatus\n\t}\n,\n\t\t\topenseaUrl,\n\t\t\tetsyUrl,\n\t\t\tsold,\n\t\t\tinventory\n\t\t}\n\t}\n': BirdBySlugQueryResult;
		'\n\t*[_type == "bird" && defined(slug.current)] | order(commonName asc) {\n\t\tcommonName,\n\t\t"slug": slug.current\n\t}\n': BirdNavQueryResult;
		'\n\t*[_type == "post" && defined(publishedAt)] | order(publishedAt desc) {\n\t\t_id, title, "slug": slug.current, excerpt, category, tags, publishedAt\n\t}\n': AllPostsQueryResult;
		'\n\t*[_type == "post" && slug.current == $slug][0] {\n\t\t_id, title, "slug": slug.current, excerpt, category, tags, publishedAt, body\n\t}\n': PostBySlugQueryResult;
		'\n\t*[_type == "post" && defined(slug.current) && defined(publishedAt)].slug.current\n': PostSlugsQueryResult;
		'\n\t*[_type == "card" && defined(slug.current)].slug.current\n': CardSlugsQueryResult;
		'\n\t*[_type == "rarityTier"] | order(level asc) {\n\t\t_id,\n\t\tlevel,\n\t\tlabel,\n\t\tmaxPhysical,\n\t\tmaxDigital\n\t}\n': RarityTiersQueryResult;
		'\n\t*[_type == "post" && defined(publishedAt)] | order(publishedAt desc)[0...3] {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\texcerpt,\n\t\tcategory,\n\t\ttags,\n\t\tpublishedAt,\n\t\tcoverImage {\n\t\t\talt,\n\t\t\tasset->{ _id, url, "lqip": metadata.lqip, "aspectRatio": metadata.dimensions.aspectRatio }\n\t\t}\n\t}\n': RecentPostsQueryResult;
		'\n\t*[_type == "nomination" && status == "approved"]\n\t\t| order(voteCount desc, birdName asc)[0...5] {\n\t\t_id,\n\t\tbirdName,\n\t\t"slug": slug.current,\n\t\tvoteCount\n\t}\n': NominationsQueryResult;
		'\n\t*[_id == "siteSettings"][0] {\n\t\tnavLinks[] { _key, label, href },\n\t\tsocialLinks[] { _key, platform, url },\n\t\tcontactEmail,\n\t\tfaqs[] { _key, question, answer },\n\t\tctaHeading,\n\t\tctaBody,\n\t\tctaButtonLabel,\n\t\tctaButtonHref,\n\t\tnextDropAt\n\t}\n': SiteSettingsQueryResult;
	}
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
	interface SanityQueries extends globalThis.SanityQueries {}
}
